let imgLoaded=false,sourceCanvas=null,selection=null,lastResult=null,apiToken=null,cloudCalibration=null;
const $=id=>document.getElementById(id), STORE='toxinova_h2s_records_v2';
const DEMO=[{id:'W-128',date:'07 Sep 2026 · 08:30',dose:12.6,twa:1.58,status:'Synced'},{id:'W-129',date:'07 Sep 2026 · 09:10',dose:24.8,twa:3.10,status:'Synced'},{id:'W-130',date:'07 Sep 2026 · 10:00',dose:31.2,twa:3.90,status:'Synced'}];
const API='/api';
async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(apiToken)headers.Authorization='Bearer '+apiToken;const r=await fetch(API+path,{...options,headers});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||'API error');return r.json()}
async function authenticate(){try{const x=await api('/login',{method:'POST',body:JSON.stringify({username:'supervisor',password:'super123'})});apiToken=x.token;cloudCalibration=(await api('/calibration')).points;return true}catch(e){return false}}
function getRecords(){try{let x=JSON.parse(localStorage.getItem(STORE));if(Array.isArray(x))return x}catch(e){}saveRecords(DEMO);return DEMO.slice()}
function saveRecords(r){localStorage.setItem(STORE,JSON.stringify(r))}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function renderAll(){const records=getRecords(),hist=$('historyTable');while(hist.rows.length>1)hist.deleteRow(1);records.slice().reverse().forEach(r=>{let row=hist.insertRow(-1),c=r.status==='Synced'?'low':'info';row.innerHTML=`<td>${esc(r.id)}</td><td>${esc(r.date)}</td><td>${Number(r.dose).toFixed(1)} ppm-h</td><td>${Number(r.twa).toFixed(2)} ppm</td><td><span class="badge ${c}">${esc(r.status)}</span></td>`});const pending=records.filter(r=>r.status==='Pending Sync').length;$('kpiScans').textContent=records.length;$('kpiPending').textContent=pending;$('hsePending').textContent=pending;if($('hseTable')){const h=$('hseTable');while(h.rows.length>1)h.deleteRow(1);records.slice().reverse().forEach(r=>{let row=h.insertRow(-1),level=r.twa>=4?'High-priority review':r.twa>=2?'Monitor':'Normal',lc=r.twa>=4?'high':r.twa>=2?'moderate':'low',sc=r.status==='Synced'?'low':'info';row.innerHTML=`<td>${esc(r.id)}</td><td>${Number(r.dose).toFixed(1)} ppm-h</td><td>${Number(r.twa).toFixed(2)} ppm</td><td><span class="badge ${lc}">${level}</span></td><td><span class="badge ${sc}">${esc(r.status)}</span></td>`})}$('syncText').textContent=pending?`${pending} record${pending>1?'s':''} waiting for synchronization.`:'All records synchronized.';$('syncBar').style.width=records.length?`${Math.round((records.length-pending)/records.length*100)}%`:'0%';if($('net')){$('net').className='status '+(navigator.onLine?'online':'offline');$('net').textContent=navigator.onLine?'● Online • Backend connected':'● Offline mode active'}}
async function refreshCloud(){if(!apiToken)return;try{const cloud=await api('/records');saveRecords(cloud);renderAll();$('hseActive').textContent=(await api('/hse')).activeWorkers}catch(e){}}
async function syncPending(){if(!navigator.onLine){renderAll();return false}let local=getRecords(),pending=local.filter(x=>x.status==='Pending Sync');if(apiToken&&pending.length){try{const out=await api('/sync',{method:'POST',body:JSON.stringify({records:pending})});saveRecords(out.records);renderAll();return true}catch(e){}}if(apiToken){await refreshCloud();return false}local.forEach(x=>{if(x.status==='Pending Sync')x.status='Synced'});saveRecords(local);renderAll();return pending.length>0}
document.querySelectorAll('.nav').forEach(n=>n.addEventListener('click',()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));n.classList.add('active');document.querySelectorAll('.section').forEach(s=>s.classList.remove('active'));$(n.dataset.tab).classList.add('active');renderAll()}));
$('photo').addEventListener('change',()=>{const f=$('photo').files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{$('preview').onload=()=>{imgLoaded=true;$('preview').style.display='block';$('phText').style.display='none';sourceCanvas=document.createElement('canvas');sourceCanvas.width=$('preview').naturalWidth;sourceCanvas.height=$('preview').naturalHeight;sourceCanvas.getContext('2d').drawImage($('preview'),0,0);selection=null;$('selectionMsg').textContent='Image loaded. Click Auto-detect sensing strip.';resetResult()};$('preview').src=rd.result};rd.readAsDataURL(f)});
$('auto').onclick=autoDetect;$('analyze').onclick=analyze;$('clear').onclick=()=>{selection=null;resetResult();$('selectionMsg').textContent='Selection cleared.'};
function autoDetect(){if(!imgLoaded){alert('Choose the wristband photo first.');return}const W=sourceCanvas.width,H=sourceCanvas.height,s=document.createElement('canvas'),scale=Math.min(1,700/W,500/H);s.width=Math.max(1,Math.round(W*scale));s.height=Math.max(1,Math.round(H*scale));const sc=s.getContext('2d',{willReadFrequently:true});sc.drawImage(sourceCanvas,0,0,s.width,s.height);const d=sc.getImageData(0,0,s.width,s.height).data;let minX=s.width,minY=s.height,maxX=-1,maxY=-1,count=0;for(let y=0;y<s.height;y+=2)for(let x=0;x<s.width;x+=2){let i=(y*s.width+x)*4,r=d[i],g=d[i+1],b=d[i+2],mx=Math.max(r,g,b),mn=Math.min(r,g,b);if(r>75&&g>45&&r>=g*.82&&g>b*1.08&&mx-mn>18){minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y);count++}}if(count<25){alert('Automatic detection could not confidently find the colored strip.');return}const inv=1/scale,pad=8*inv;selection={x:Math.max(0,minX*inv-pad),y:Math.max(0,minY*inv-pad),w:Math.min(W,(maxX-minX)*inv+2*pad),h:Math.min(H,(maxY-minY)*inv+2*pad)};$('selectionMsg').textContent='✓ Sensing strip detected automatically. Ready to analyze.';analyze()}
async function analyze(){if(!imgLoaded){alert('Choose a wristband photo first.');return}if(!selection){alert('Click Auto-detect sensing strip first.');return}const c=sourceCanvas.getContext('2d',{willReadFrequently:true}),x=Math.max(0,Math.floor(selection.x)),y=Math.max(0,Math.floor(selection.y)),w=Math.min(sourceCanvas.width-x,Math.floor(selection.w)),h=Math.min(sourceCanvas.height-y,Math.floor(selection.h)),d=c.getImageData(x,y,w,h).data,p=[];for(let i=0;i<d.length;i+=4){let r=d[i],g=d[i+1],b=d[i+2],mx=Math.max(r,g,b),mn=Math.min(r,g,b);p.push([r,g,b,mx,mn])}p.sort((a,b)=>(a[3]+a[4])-(b[3]+b[4]));let lo=Math.floor(p.length*.1),hi=Math.max(lo+1,Math.ceil(p.length*.9)),R=0,G=0,B=0,n=0;for(let i=lo;i<hi;i++){R+=p[i][0];G+=p[i][1];B+=p[i][2];n++}let rgb=[R/n,G/n,B/n],lab=rgbToLab(...rgb),ref=[+$('rL').value,+$('rA').value,+$('rB').value],de=deltaE(lab,ref),raw=mapDose(de),temp=+$('temp').value||30,hum=+$('hum').value||65,hours=+$('hours').value||8,env=1+(temp-30)*.004+(hum-65)*.001,dose=Math.max(0,raw*env*(+$('factor').value||1)),twa=dose/hours;lastResult={dose,twa,rgb,lab,de,worker:$('worker').value||'Unknown'};$('rgb').textContent=rgb.map(v=>Math.round(v)).join(', ');$('lab').textContent=lab.map(v=>v.toFixed(1)).join(', ');$('de').textContent=de.toFixed(1);$('dose').textContent=dose.toFixed(1);$('twa').textContent=twa.toFixed(2)+' ppm';$('swatch').style.background=`rgb(${rgb.map(v=>Math.round(v)).join(',')})`;$('overviewDose').textContent=dose.toFixed(1);$('overviewTwa').textContent=twa.toFixed(2)+' ppm';await addRecord(lastResult);toast(apiToken&&navigator.onLine?'Exposure calculated and stored in backend.':'Exposure calculated and stored locally. Pending sync until connection returns.')}
function rgbToLab(R,G,B){let r=R/255,g=G/255,b=B/255;r=r<=.04045?r/12.92:Math.pow((r+.055)/1.055,2.4);g=g<=.04045?g/12.92:Math.pow((g+.055)/1.055,2.4);b=b<=.04045?b/12.92:Math.pow((b+.055)/1.055,2.4);let X=(r*.4124+g*.3576+b*.1805)/.95047,Y=r*.2126+g*.7152+b*.0722,Z=(r*.0193+g*.1192+b*.9505)/1.08883,f=t=>t>.008856?Math.cbrt(t):7.787*t+16/116;X=f(X);Y=f(Y);Z=f(Z);return[116*Y-16,500*(X-Y),200*(Y-Z)]}
function deltaE(a,b){return Math.sqrt((a[0]-b[0])**2+(a[1]-b[1])**2+(a[2]-b[2])**2)}
function mapDose(de){const p=cloudCalibration&&cloudCalibration.length?cloudCalibration:[[0,0],[15,5],[30,10],[45,20],[60,35],[75,55]];const pts=p.map(x=>Array.isArray(x)?x:[x.de,x.dose]);if(de<=0)return 0;for(let i=1;i<pts.length;i++)if(de<=pts[i][0]){let[x1,y1]=pts[i-1],[x2,y2]=pts[i];return y1+(de-x1)*(y2-y1)/(x2-x1)}let[x1,y1]=pts[pts.length-2],[x2,y2]=pts[pts.length-1];return y2+(de-x2)*(y2-y1)/(x2-x1)}
function resetResult(){['dose','rgb','lab','de','twa'].forEach(id=>$(id).textContent='—');$('swatch').style.background=''}
async function addRecord(r){const local=getRecords();const record={id:r.worker,date:new Date().toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})+' · Current shift',dose:r.dose,twa:r.twa,status:(apiToken&&navigator.onLine)?'Synced':'Pending Sync'};local.push(record);saveRecords(local);renderAll();if(apiToken&&navigator.onLine){try{await api('/records',{method:'POST',body:JSON.stringify(record)});await refreshCloud()}catch(e){record.status='Pending Sync';saveRecords(local);renderAll()}}}
async function sync(){if(!navigator.onLine){toast('No network connection. Records remain stored locally.');renderAll();return}toast((await syncPending())?'Pending records synchronized with backend.':'Everything is already synchronized.')}
$('sync').onclick=sync;$('hseSync').onclick=sync;$('clearHistory').onclick=()=>{localStorage.removeItem(STORE);saveRecords([]);renderAll();toast('Local prototype records cleared. Backend records remain available.')} ;window.addEventListener('online',async()=>{toast('Network restored. Synchronizing pending records...');await syncPending()});window.addEventListener('offline',()=>{renderAll();toast('Network lost. New scans will be stored locally.')});
function toast(s){$('toast').textContent=s;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',2500)}
(async()=>{renderAll();const ok=await authenticate();if(ok){$('net').textContent=navigator.onLine?'● Online • Backend connected':'● Offline • Local cache active';if(navigator.onLine)await refreshCloud();await syncPending()}else{toast('Backend unavailable. Running in offline prototype mode.')}})();
